### ISSUE TITLE
Adding MANIFEST.MF Main-Class

### ISSUE THREAD

**Issue by sebfz1** [acciente/oacc-core#20]
Hi,

I think it could be useful to add a main-class manifest attribute, that points to `SQLAccessControlSystemInitializer`, so it will ease the command line syntax...

Thanks & best regards,
Sebastien

**Comment by fspinnenhirn** [comment]
I agree - that would be neat, Sebastien!

Unfortunately, there's a reason we're not setting it as the main-class of the jar file right now:  
An executable jar-file _must_ contain all its dependencies - it ignores any additional classpath you specify. 
The `SQLAccessControlSystemInitializer` will have to interact with your database, which means it has to locate the database driver for the actual DBMS you're using. 
And we simply can't bundle database drivers into the OACC jar file. :neutral_face:

**Comment by sebfz1** [comment]
Hi Fabian,

> An executable jar-file must contain all its dependencies - it ignores any additional classpath you specify. 

You are absolutely right! I had completely forgot this...

Thanks & best regards,
Sebastien.

**Comment by renebareno** [comment]
this works for me : java -cp "acciente-oacc-2.0.0-rc.7.jar;mariadb-java-client-7.5.8.jar;jasypt-1.9.2.jar;" com.acciente.oacc.sql.SQLAccessControlSystemInitializer -dburl=jdbc:mysql://localhost/TEST_OACC?sessionVariables=sql_mode='NO_AUTO_VALUE_ON_ZERO,STRICT_TRANS_TABLES,NO_ENGINE_SUBSTITUTION'  -dbuser=oaccuser -dbpwd=oaccpwd -oaccsystempwd=mipwd 
Anyway I create 'TEST_OACC' db, since is the one 'SQLAccessControlSystemInitializer' looks for.
