### ISSUE TITLE
Compilation errors in test classes when imported in eclipse

### ISSUE THREAD

**Issue by mpujari** [acciente/oacc-core#26]
Compilation errors when importing the project in eclipse for two test classes TestSQLAccessControlContextFactory and TestSQLAccessControlSystemInitializer

The above two classes are calling "com.ibm.icu.impl.Assert.fail" methods but it seems we need to replace this with "org.junit.Assert.fail" (and in pom we never have dependency to icu4j)

**Comment by fspinnenhirn** [comment]
Thanks for reporting these incorrect dependencies, Mahesh!
I've replaced the wrong import statements with the correct ones that point at JUnit.

We currently don't list the (rather large) icu4j library as a dependency in OACC's POM file because it is only relevant if someone uses OACC's built-in secure password authentication provider and wants to prevent a cleanable `char[]` password being turned into a temporary `String` during unicode character normalization [within the jasypt library](http://www.jasypt.org/faq.html#store-pbe-passwords-strings). We'll make this more transparent in our documentation, shortly.
